name: build_so
on:
  push:
    branches:
    - main
    - master
    - release/*
jobs:
  run_make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Make
        run: make -j${nproc}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: game_binary
          path: game*.so
